- buildout.cfg
- config_pdf.yaml.in
- development.ini.in
- mapserver/fonts.txt
- production.ini.in
no need to review. just some new variables
> Defaultbaselayer

- config_pdf.yaml.in
This is part of the mapfish print integration.
@voisardf, I am merging this into the mapfish_print branch, so don't worry...
> Add localhost urls

- config_pdf.yaml.in
Nothing big. - Added threre new options to the pdf configuration, a lot of comments and changed the topic name scheme to avoid possible confusion with existing cantonal cadastre number.
@kalbermattenm : please give it a quick look. thanks
This completes core PR https://github.com/sitn/crdppf_core/pull/81
> added new options to pdf configuration file

- config_pdf.yaml.in
This will be merged into the mapfish_print branch.
NO NEED TO REVIEW.
I added a comment to the 2.0 release draft for that (https://github.com/sitn/crdppf_core/releases/tag/untagged-aae53b341f2a9e309153)
> Add WMTS getCapabilities variable

- config_pdf.yaml.in
I will update the release note draft accordingly.
Merging into the mapfish_print branch
> Change print URL

- config_pdf.yaml.in
Merging master into mapfish_print branch
> Update Mapfish print branch

- mapserver/crdppf.map.in
Just a minor modification to get the mapfile Mapserver7 compatible. No need to review.
> replaced annotation by point for Maperver 7

- buildout.cfg
Title says it all
Please note that you will have to add something like this in the `vars` section of your buildout file:
```
tomcat_webapp_folder = C:/WHEREEVERTOMCATISINSTALLED/webapps
```
> Add Tomcat start & stop sections to buildout

- config_db.yaml.in
after synchronazing tables between db's that's  the new valid definition
no need to review. merging right away
> changing the bloody mess in the config file

- mapserver/crdppf.map.in
Just fixed an representation issue. no need to review.
> Fixed a issue with polygon fill

- config_pdf.yaml.in
Title says it all....
There are also some style improvements ;-)
> Update crdppf to 1.1.3 core

- crdppfportal/__init__.py
To be compatible with what is coming in PR https://github.com/sitn/crdppf_core/pull/100
> Remove unused renderer

- mapserver/crdppf.map.in
> Update mo23 attribute and style of piscine

- apache/mapserver.conf.in
- apache/wsgi.conf.in
- buildout.cfg
This enables to use the CRDPPF project with Apache 2.4
Merging (tested on NESITND1)
> Update config for Apache 2.4

- mapserver/crdppf.map.in
> adapted layer names and new layer

- config_pdf.yaml.in
- mapserver/crdppf.map.in
This PR adds different layers needed for the separte cadastral map on the topic pages
> cadastral map - configured wms for cadastral topic map

- mapserver/crdppf.map.in
- mapserver/crdppf.sym
> Create duplicated layers so that WMS can be used by CANEPO

- mapserver/crdppf.map.in
simple name change no need for review
> renamed legend entry for r108

- mapserver/crdppf.map.in
> fixed typos in mapfile

- mapserver/crdppf.map.mako
> fixed dbconnexion in mako

- config_pdf.yaml.mako
title says it all. This one is for the master and make.
> configuration for HTTPS

- config_pdf.yaml.in
> changed configuration for HTTPS

- apache/wsgi.conf.mako
> removed globals var for compatibility issues

- mapserver/crdppf.map.mako
Adds a fill for natural hazard zones for better understanding of the map
> Naturalhazardfill

- config_pdf.yaml.mako
adds a new variable to set the buffer size around the real estate on the map
> added map buffer value to configuration

- config_pdf.yaml.mako
> config to set archiving of pdf

- config_pdf.yaml.mako
pdf config file with pdf_archive variable as used by JU
> configuration for linux adaption

- setup.py
Version change and adding a recommendation for the pyramid_oereb version
> recommended pyramid_oereb version

- config_pdf.yaml.mako
> removed duplicated parameter config for archive_path

- config_db.yaml
> added attribute definition for egrid

- config_db.yaml
- config_pdf.yaml.mako
in order for it to work.
Merging
> [Py3] - Update to master & adapt config

- crdppfportal/table2model_match.py
just moved the file, completes PR : https://github.com/sitn/crdppf_core/pull/16
> moved table2model match from core to specific part

- pyramid_oereb_standard.yml.mako
just some small fixes. title says it all
> latest configuration of pyramid_oereb_standard.yml

- mapserver/crdppf.map.mako
> Just a small adaption of at02 layer opacity

- setup.py
Update to latest pyramid_oereb version
> Version 1.5 of pyramid_oereb

- pyramid_oereb_standard.yml.mako
title says it all, just basic configuration
> adapted legal status values for civil aviation2

- pyramid_oereb_standard.yml.mako
trivial change for attributes values
> changed legale state values for federal topic

- pyramid_oereb_standard.yml.mako
> fixed label for layer airports security zones

- pyramid_oereb_standard.yml.mako
> Get rid of the c2c background WMTS layers

- pyramid_oereb_standard.yml.mako
- setup.py
Update of the pyramid_oereb version
Replacement of the certification reference we do not have in NE as far as I know
> Update to pyramid_oereb v1.5.1

- mapserver/crdppf.map.mako
Just different modifications of layerorder, styles, opacity and labelling for new land use data structure
> Landuse fixes

- mapserver/crdppf.map.mako
> sorted mapfile classes according to SAT demand

- mapserver/crdppf.map.mako
> fixed some landuse classes

- mapserver/crdppf.map.mako
Pure mapfile adjustement - if you want to have a look.
> fixed display of land planning content accordingly to label modification

- mapserver/crdppf.map.mako
> another change for the land use plan

- setup.py
Upgrade to latest version of pyramid_oereb 1.7.4 (bugfix of 1.7.4) and crdppf 3.1
> integrate latest version of pyramid_oereb

- crdppfportal/models.py
- crdppfportal/table2model_match.py
- development.ini.mako
Depends on https://github.com/sitn/crdppf_core/pull/198
> Refactor models & DBSession

- mapserver/crdppf.map.mako
Trivial, just a legend change.
> modified legend entry as asked by OPMS

- config_pdf.yaml.mako
- crdppfportal/table2model_match.py
- mapserver/crdppf.map.mako
- pyramid_oereb_standard.yml.mako
- setup.py
Adds the necessary elements for the new contaminated military sites data
> Polluted military sites

- mapserver/crdppf.map.mako
> removed class of patrimoine architectural

- mapserver/crdppf.map.mako
replacing symbol. trivial again
> Remove pa01 class

- config_pdf.yaml.mako
title says it all, corresponds to PR https://github.com/sitn/crdppf_core/pull/211 of crdppf_core
> added needed variables for bbox_refactoring

- mapserver/crdppf.map.mako
> just changed symbol size

- mapserver/crdppf.map.mako
> adapted symbol size to scale

- mapserver/crdppf.map.mako
Mostly styling and improving. thanks for a quick look
> added missing style tags and improved structure/spacing
